version: 2.1
#orbs:
#  codecov: codecov/codecov@3.0.0

jobs:
  build-and-test:
    parameters:
      rust-version:
        type: string
        default: "stable"
      debian-version:
        type: string
        default: "buster"
    docker:
      - image: rust:<< parameters.rust-version >>-<< parameters.debian-version >>
    environment:
      RUSTFLAGS: '-D warnings'
    steps:
      - checkout
      - run:
          name: Rust Version
          command: rustc --version; cargo --version
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
  coverage:
    machine: true
    steps:
      - checkout
      - run:
          name: Generate Coverage
          command: >
              docker run
              --security-opt seccomp=unconfined
              -v "${PWD}:/home"
              akubera/rust-codecov:1.54.0-buster
              sh -c 'cargo test -q && kcov-rust && upload-kcov-results-to-codecov'
       # - codecov/upload

workflows:
  version: 2
  build-and-test:
   jobs:
     - build-and-test:
         matrix:
             parameters:
                rust-version:
                   - "1.53.0"
                   - "1.54.0"
  
