version: 2.1
orbs:
#   codecov: codecov/codecov@3.0.0
  rust: circleci/rust@1.5.0

jobs:
  build-and-test:
    parameters:
      rust-version:
        type: string
      debian-version:
        type: string
        default: "buster"
    docker:
      - image: circleci/rust:<< parameters.rust-version >>-<< parameters.debian-version >>
    environment:
      RUSTFLAGS: '-D warnings'
    steps:
      - checkout
      - run:
          name: Rust Version
          command: rustc --version; cargo --version
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test

  upload-coverage:
    parameters:
      rust-version:
        type: string
      debian-version:
        type: string
        default: "buster"
    machine: true
    steps:
      - checkout
      - run:
          name: Echo Coverage Command
          command: >
            echo
            docker run
            --security-opt seccomp=unconfined
            -v "${PWD}:/home"
            -e CI=true
            $(bash <(curl -s https://codecov.io/env))
            akubera/rust-codecov:<< parameters.rust-version >>-<< parameters.debian-version >>
            sh -c 'cargo test -q && kcov-rust && upload-kcov-results-to-codecov'
      - run:
          name: Generate Coverage
          command: >
              docker run
              --security-opt seccomp=unconfined
              -v "${PWD}:/home"
              -e CI=true
              $(bash <(curl -s https://codecov.io/env))
              akubera/rust-codecov:<< parameters.rust-version >>-<< parameters.debian-version >>
              sh -c 'cargo test -q && kcov-rust && upload-kcov-results-to-codecov'
      - store_artifacts:
          path: target/cov
      - store_test_results:
          path: target/cov

  misc:
    docker:
      - image: circleci/rust:stable
    steps:
      - checkout
      - rust/format
      - rust/clippy
      - rust/test

workflows:
  version: 2
  build-and-test:
    jobs:
    # - build-and-test:
    #     rust-version: "1.34.0"
    #     debian-version: "stretch"
    - build-and-test:
        matrix:
          parameters:
            rust-version:
            - "nightly"
            - "beta"
            - "stable"
            - "1.50.0"
            - "1.40.0"
    - upload-coverage:
        rust-version: "1.54.0"
    - misc
